apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-deployment
  labels:
    app: otus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus
  template:
    metadata:
      labels:
        app: otus
    spec:
      containers:
        - name: otus
          image: sdukshis/otus_cicd:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: otus-service
  labels:
    app: otus
spec:
  selector:
    app: otus
  ports:
    - name: otus
      protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: main.otus-mlops.filonovpv.name
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: otus-service
              port:
                number: 8000

