name: K8s deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sdukshis
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: sdukshis/otus_cicd:${{ event.run_id }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: default
    
      - name: Deploy k8s
        uses: jtalk/k8s-deploy@v2
        with:
          namespace: '${{ env.GITHUB_REF_NAME }}'
          images: 'sdukshis/otus_cicd:${{ event.run_id }}'
          manifests: |
              k8s/otus.yml
          kubectl-version: 'latest'
