name: K8s deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sdukshis
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: sdukshis/otus_cicd:${{ env.GITHUB_REF_NAME }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
